/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  account: {
    Profile: () => import('#controllers/account/profile_controller'),
  },
  auth: {
    AccessToken: () => import('#controllers/auth/access_token_controller'),
    NewAccount: () => import('#controllers/auth/new_account_controller'),
  },
  clients: {
    Clients: () => import('#controllers/clients/clients_controller'),
  },
  gateways: {
    Gateways: () => import('#controllers/gateways/gateways_controller'),
  },
  products: {
    Products: () => import('#controllers/products/products_controller'),
  },
  purchases: {
    Purchase: () => import('#controllers/purchases/purchase_controller'),
  },
  users: {
    Users: () => import('#controllers/users/users_controller'),
  },
}
